<a href="https://colab.research.google.com/github/kimhalyn/Colab/blob/main/1_2_NumpyTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜: 2021/02/01
이름: 김하린
내용: 파이썬 Numpy 수치해석 라이브러리 실습하기
"""

'\n날짜: 2021/02/01\n이름: 김하린\n내용: 파이썬 Numpy 수치해석 라이브러리 실습하기\n'

In [ ]:
import numpy as np

In [ ]:
#numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
v2 = np.arange(5)
v3 = np.arange(10)

print('v1: ', v1)
print('v2: ', v2)
print('v3: ', v3)

v1:  [1 2 3 4 5]
v2:  [0 1 2 3 4]
v3:  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
#0 ~ 1사이에 임의의 실수
rand1 = np.random.rand(100)

#표준정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)

#0 ~ 9사이의 임의의 정수
rand3 = np.random.randint(10)

In [ ]:
rand1

array([0.29271923, 0.49686773, 0.95962637, 0.967901  , 0.10945606,
       0.33714032, 0.24886179, 0.84441985, 0.77658866, 0.5224184 ,
       0.08085834, 0.7595242 , 0.89580677, 0.98872334, 0.13477866,
       0.78767638, 0.45335406, 0.84169001, 0.21157724, 0.80560084,
       0.99619777, 0.20075354, 0.25049505, 0.53706316, 0.08783371,
       0.67863265, 0.21670565, 0.13642586, 0.31151567, 0.3497725 ,
       0.59373299, 0.30148888, 0.55166775, 0.11981634, 0.19671157,
       0.71805714, 0.1064891 , 0.62129887, 0.79772163, 0.61074218,
       0.03802108, 0.53297002, 0.05728588, 0.42775002, 0.48615777,
       0.76008999, 0.03494609, 0.2367889 , 0.81372198, 0.98646577,
       0.43163544, 0.58047503, 0.77432097, 0.07757005, 0.94822981,
       0.88943492, 0.8872623 , 0.00662991, 0.64668576, 0.99639712,
       0.44380323, 0.54141146, 0.27499384, 0.16707751, 0.46061059,
       0.4535879 , 0.86090584, 0.68750859, 0.78432734, 0.03097531,
       0.77340567, 0.11228691, 0.37324091, 0.79645002, 0.65539

In [ ]:
rand2

array([ 1.10722782,  0.69288964, -0.73584895,  2.03378818, -0.68713736,
        1.88451777, -1.28192656,  1.17593558,  1.7605378 ,  0.470854  ,
        1.32829918,  0.18125079,  0.24543143, -0.22434616, -2.10003048,
       -0.21530789, -0.59528799, -0.94216662, -0.96934962,  0.06358975,
       -0.03921869, -1.45768884,  0.61246579, -0.81264091, -0.65617218,
       -0.66539108,  0.73277491, -1.00968423, -0.53289521, -1.5933889 ,
       -1.15314136,  1.28327378, -0.19987009,  0.60740494, -0.85472309,
        0.18257906,  0.1328495 , -0.25224384,  0.17056223,  0.2868928 ,
        0.87705853,  0.71660359,  0.83602922, -2.21326365,  1.11518555,
       -1.85700888,  0.03742578,  1.21805607,  0.99302743, -0.081016  ,
        0.61327495, -1.50294385, -2.56020946, -1.22138614,  1.13765573,
        0.06474071, -0.38518444,  0.50624617,  2.18759961,  0.68470033,
        0.20240304, -0.85179762,  0.86385115,  1.5746252 ,  0.12399683,
        0.71388771, -1.11318007,  0.49374019,  0.73654814, -0.13

In [ ]:
rand3

6

In [ ]:
#행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#전치행렬 - 행/열을 바꿈
tm1 = m1.T
print(tm1)

tm2 = m2. transpose()
print(tm2)

In [ ]:
#단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#행렬 인덱싱 - 행렬에서 내가 원하는 성분을 출력한다
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)


print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
